
version: '2'

networks:
  proxy:
    external: true

services:
  cgit:
    build: cgit-aarch64
    container_name: cgit
    restart: unless-stopped
    volumes:
      - $SYNCDIR/src:/git
    networks:
      - proxy
    labels:
      traefik.frontend.rule: "Host:git.$DOMAIN"
      traefik.port: "80"
  dir-repo:
    build: rclone-aarch64
    container_name: dir-repo
    restart: unless-stopped
    command: "--config '/config/rclone.conf' serve http '$RCLONE_REMOTE' --addr '0.0.0.0:8080'"
    volumes:
      - $CONFDIR/rclone:/config
    networks:
      - proxy
    labels:
      traefik.frontend.rule: "Host:repo.$DOMAIN"
      traefik.port: "8080"
  flexget:
    build: flexget-aarch64
    container_name: flexget
    restart: unless-stopped
    volumes:
      - $CONFDIR/flexget:/config
      - $DOWNDIR:/input
      - $STORDIR:/output
  jekyll:
    build: jekyll-aarch64
    container_name: jekyll
    restart: unless-stopped
    volumes:
      - $SYNCDIR/src/blog:/srv/jekyll
    networks:
      - proxy
    labels:
      traefik.frontend.rule: "Host:$DOMAIN,blog.$DOMAIN,www.$DOMAIN"
      traefik.port: "4000"
  kms-server:
    build: kms-server-aarch64
    container_name: kms-server
    restart: unless-stopped
    ports:
      - 1688:1688
  ouroboros:
    image: pyouroboros/ouroboros:1.3.1-arm64 
    container_name: ouroboros
    restart: unless-stopped
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - SELF_UPDATE=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  syncthing:
    image: lsioarmhf/syncthing-aarch64
    container_name: syncthing
    restart: unless-stopped
    volumes:
      - $CONFDIR/syncthing:/config
      - $SYNCDIR:/vault
      - $SAVEDIR:/saves
    ports:
      - 22000:22000
      - 21027:21027/udp
    environment:
      - PGID=$PGID
      - PUID=$PUID
    networks:
      - proxy
    labels:
      traefik.frontend.rule: "Host:sync.$DOMAIN"
      traefik.port: "8384"
  traefik:
    image: arm64v8/traefik
    container_name: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFDIR/traefik/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
  transmission:
    image: lsioarmhf/transmission-aarch64
    container_name: transmission
    restart: unless-stopped
    volumes:
      - $CONFDIR/transmission:/config
      - $DOWNDIR:/downloads
      - $SYNCDIR/import:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    networks:
      - proxy
    labels:
      traefik.frontend.rule: "Host:tor.$DOMAIN"
      traefik.port: "9091"

