
version: '2'

networks:
  proxy:
    external: true

services:
  flexget:
    build: flexget-aarch64
    container_name: flexget
    restart: unless-stopped
    volumes:
      - $CONFDIR/flexget:/config
      - $DOWNDIR:/input
      - $STORDIR:/output
  jekyll:
    build: jekyll-aarch64
    container_name: jekyll
    restart: unless-stopped
    volumes:
      - $SYNCDIR/src/blog:/srv/jekyll
    networks:
      - proxy
    labels:
      traefik.frontend.rule: "Host:$DOMAIN,blog.$DOMAIN,www.$DOMAIN"
      traefik.port: "4000"
  traefik:
    image: arm64v8/traefik
    container_name: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFDIR/traefik/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
  transmission:
    image: lsioarmhf/transmission-aarch64
    container_name: transmission
    restart: unless-stopped
    volumes:
      - $CONFDIR/transmission:/config
      - $DOWNDIR:/downloads
      - $SYNCDIR/import:/watch
    ports:
      - 51413:51413
      - 51413:51413/udp
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
    networks:
      - proxy
    labels:
      traefik.frontend.rule: "Host:tor.$DOMAIN"
      traefik.port: "9091"

