
version: '2'

networks:
  proxy:
    external: true

services:
  flexget:
    build: flexget-aarch64
    container_name: flexget
    restart: unless-stopped
    volumes:
      - $CONFDIR/flexget:/config
      - $DOWNDIR:/input
      - $STORDIR:/output
  traefik:
    image: arm64v8/traefik
    container_name: traefik
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $CONFDIR/traefik/traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
